# Setup
title:               Blog de hockey
tagline:             Projet pour le cours IFT6758
description:         Milestone 1
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

theme: minima

# About/contact
author:
  name:              Qi Li
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
markdown: kramdown
kramdown:
  math_engine: mathjax
future: true
# Keep or include the figures directory
include:
  - figures
keep_files:
  - figures